apiVersion: v1
kind: Pod
metadata:
  name: app-client
  namespace: mi-app-segura
  labels:
    app: client # Etiqueta para que la NetworkPolicy lo identifique
spec:
  containers:
  - name: net-utils
    image: busybox # Una imagen con herramientas de red para pruebas
    command: ["sleep", "3600"]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-allow-client
  namespace: mi-app-segura
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: redis # Selecciona el pod de Redis
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: client # Permite tráfico SOLO desde pods con esta etiqueta
    ports:
    - protocol: TCP
      port: 6379 # En el puerto de Redis