auth:
  enabled: true
  password: "MiPasswordSegura123"

master:
  podSecurityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsNonRoot: true
    allowPrivilegeEscalation: false

replica:
  replicaCount: 0 # Deshabilitamos las réplicas para simplificar la demo

sentinel:
  enabled: false # Deshabilitamos Sentinel para simplificar